name: Lint on Push to feat/ Branches

on:
  push:
    branches:
      - 'feat/*'

jobs:
  lint:
    name: Run npm run lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '18' # You can change this to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint